extends Node

enum HEALTH_STATUS { NORMAL, INVINCIBLE, POISON, FIRE, DEAD }
enum HEALTH_EFFECT { NONE, POISON, FIRE }
enum HEALTH_DAMAGE_TYPE { NONE, POISON, FIRE }

enum MANA_STATUS { NORMAL, FAST, DRAIN, NO_COST }
enum MANA_EFFECT { NONE, DRAIN }